swagger: '2.0'
info:
  title: MOVIES REST
  description: 'Node.js course'
  version: 1.0.0
host: 'localhost:5000'
basePath: /service/
consumes:
  - application/json
produces:
  - application/json
tags:
  - name: users
    description: Users operations

paths:
  /movies:
    get:
      tags:
        - movies
      summary: Get all movies
      x-swagger-router-controller: movies.get
      responses:
        '200':
          description: movie
          schema:
            $ref: '#/definitions/movie'



definitions:
  movie:
    type: object
    properties:
      _id:
        type: string
      name:
        type: string
      image:
        type: string

